# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/:year/:month/:day/:title/

# Setup
title:            "Jorgos Lambrinidis"
tagline:          "Jorgos Lambrinidis's Blog"
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      '.NET developer, interested in <a href="https://www.asp.net/">ASP.NET</a>
url:              https://jorgoslambrinidis.github.io
baseurl:          /
hometitle:        "Posts"

author:
  name:           'Jorgos Lambrinidis'
  url:            https://mk.linkedin.com/in/jorgos-lambrinidis-a8a67868

paginate:         5

# Custom vars
version:          1.0.0.0

logo:             /assets/home1.jpg

github:
  repo:           https://github.com/jorgoslambrinidis/jorgoslambrinidis.github.io

# Plugins
plugins:          [jekyll-paginate, jekyll-sitemap]